### ISSUE TITLE
Question: Will document scanner be available too?

### ISSUE THREAD

**Issue by MrAdex77** [gev2002/react-native-vision-camera-v3-image-labeling#1]
Hi,

I would like to ask you but couldn't find the DM button, will you add also a document scanner from ml kit to react native vision camera as a frame processor plugin?

**Comment by gev2002** [comment]
> Hi,
> 
> I would like to ask you but couldn't find the DM button, will you add also a document scanner from ml kit to react native vision camera as a frame processor plugin?

In ML Kit library scanner documents is available only for android.I will create plugin for android soon.
