### ISSUE TITLE
Update plugin

### ISSUE THREAD

**Issue by mrousavy** [gev2002/react-native-vision-camera-v3-image-labeling#2]
hey @gev2002 - I think I want to use the image labeler/object detector plugin here as a showcase for FP plugins in the documentation.

I was just wondering if you could:
- update the options to be passed to the initializer instead of the callback itself, that way its better memory controlled
- also show the direct usage of the FP (not only your camera wrapper) in the README
- and use the Frame's coordinate system

That'd be huge - I'll then use this as an example to explain how plugins work. Thank you!

**Comment by gev2002** [comment]
> hey @gev2002 - I think I want to use the image labeler/object detector plugin here as a showcase for FP plugins in the documentation.
> 
> I was just wondering if you could:
> 
> * update this plugin like the face detector plugin to use the options on init, not on plugin call
> * also show the direct usage in the README
> * and use the Frame's coordinate system
> 
> That'd be huge - I'll then use this as an example to explain how plugins work. Thank you!

Yes, I will do it Immediately.

**Comment by mrousavy** [comment]
no stress! :)

**Comment by mrousavy** [comment]
the first point is the same as @rodgomesc has pointed out in https://github.com/gev2002/react-native-vision-camera-v3-face-detection/issues/1 - only configure this in initialize, then maybe create a hook to init the plugin like `useImageLabeler(...)` - see my vision-camera-resize-plugin for an example :)

**Comment by gev2002** [comment]
@mrousavy  Hey ! The plugin for Image Labeler is Ready for usage I updated plugin.
